// <auto-generated />
using System;
using KingOfKings.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KingOfKings.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217071151_AddZonesAndExpandedContent")]
    partial class AddZonesAndExpandedContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KingOfKings.Backend.Models.ActiveCombat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResting")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTick")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MonsterSpawnId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextTick")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueuedSkillId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonsterSpawnId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ActiveCombats");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquippedSlot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequiredClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "黏稠的凝膠，可用於製作藥水。",
                            Name = "史萊姆凝膠",
                            PropertiesJson = "{}",
                            RequiredLevel = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "野鼠的尾巴，村裡的雜貨店會收購。",
                            Name = "野鼠尾巴",
                            PropertiesJson = "{}",
                            RequiredLevel = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "適合新手冒險者的戒指，提供少量屬性加成。",
                            Name = "新手之戒",
                            PropertiesJson = "{\"Str\":1,\"Int\":1,\"Wis\":1,\"Dex\":1,\"Con\":1}",
                            RequiredLevel = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = 4,
                            Description = "一把生鏽的舊劍，勉強能用。",
                            Name = "生鏽的劍",
                            PropertiesJson = "{\"Atk\":5}",
                            RequiredLevel = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "普通的木製法杖，適合初學法師。",
                            Name = "木杖",
                            PropertiesJson = "{\"Atk\":3,\"Int\":2}",
                            RequiredLevel = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "恢復 30 點生命值。",
                            Name = "生命藥水",
                            PropertiesJson = "{\"HealHp\":30}",
                            RequiredLevel = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "恢復 20 點魔力值。",
                            Name = "魔力藥水",
                            PropertiesJson = "{\"HealMp\":20}",
                            RequiredLevel = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "粗糙的狼皮，可用於製作皮革裝備。",
                            Name = "狼皮",
                            PropertiesJson = "{}",
                            RequiredLevel = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "鋒利的狼牙，常用於製作飾品或武器。",
                            Name = "狼牙",
                            PropertiesJson = "{}",
                            RequiredLevel = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "哥布林使用的短刀，雖然生鏽但仍然鋒利。",
                            Name = "生鏽短刀",
                            PropertiesJson = "{\"Atk\":8}",
                            RequiredLevel = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "基本的皮革護甲，提供不錯的防護。",
                            Name = "皮革護甲",
                            PropertiesJson = "{\"Def\":5}",
                            RequiredLevel = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "哥布林酋長的巨斧，只有戰士能夠駕馭。",
                            Name = "酋長之斧",
                            PropertiesJson = "{\"Atk\":15,\"Str\":3}",
                            RequiredClass = 0,
                            RequiredLevel = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Description = "骷髏的殘骸，散發著微弱的魔力。",
                            Name = "骨頭碎片",
                            PropertiesJson = "{}",
                            RequiredLevel = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 14,
                            Description = "腐爛的肉塊，用途不明，或許死靈法師需要它。",
                            Name = "腐肉",
                            PropertiesJson = "{}",
                            RequiredLevel = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "死靈法師的長袍，蘊含強大的魔力，只有法師能穿戴。",
                            Name = "法師長袍",
                            PropertiesJson = "{\"Def\":3,\"Int\":8,\"Wis\":5}",
                            RequiredClass = 1,
                            RequiredLevel = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Description = "濃縮的生命藥水，恢復 80 點生命值。",
                            Name = "高級生命藥水",
                            PropertiesJson = "{\"HealHp\":80}",
                            RequiredLevel = 8,
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "濃縮的魔力藥水，恢復 50 點魔力值。",
                            Name = "高級魔力藥水",
                            PropertiesJson = "{\"HealMp\":50}",
                            RequiredLevel = 8,
                            Type = 2
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.LootTableEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DropRate")
                        .HasColumnType("REAL");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonsterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("MonsterId");

                    b.ToTable("LootTableEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DropRate = 50.0,
                            ItemId = 1,
                            MaxQuantity = 2,
                            MinQuantity = 1,
                            MonsterId = 1
                        },
                        new
                        {
                            Id = 2,
                            DropRate = 60.0,
                            ItemId = 2,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 2
                        },
                        new
                        {
                            Id = 3,
                            DropRate = 100.0,
                            ItemId = 3,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 3
                        },
                        new
                        {
                            Id = 4,
                            DropRate = 15.0,
                            ItemId = 6,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 1
                        },
                        new
                        {
                            Id = 5,
                            DropRate = 15.0,
                            ItemId = 6,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 2
                        },
                        new
                        {
                            Id = 6,
                            DropRate = 30.0,
                            ItemId = 7,
                            MaxQuantity = 2,
                            MinQuantity = 1,
                            MonsterId = 3
                        },
                        new
                        {
                            Id = 7,
                            DropRate = 60.0,
                            ItemId = 8,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 4
                        },
                        new
                        {
                            Id = 8,
                            DropRate = 40.0,
                            ItemId = 9,
                            MaxQuantity = 2,
                            MinQuantity = 1,
                            MonsterId = 4
                        },
                        new
                        {
                            Id = 9,
                            DropRate = 25.0,
                            ItemId = 10,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 5
                        },
                        new
                        {
                            Id = 10,
                            DropRate = 15.0,
                            ItemId = 11,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 5
                        },
                        new
                        {
                            Id = 11,
                            DropRate = 100.0,
                            ItemId = 12,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 6
                        },
                        new
                        {
                            Id = 12,
                            DropRate = 50.0,
                            ItemId = 16,
                            MaxQuantity = 2,
                            MinQuantity = 1,
                            MonsterId = 6
                        },
                        new
                        {
                            Id = 13,
                            DropRate = 70.0,
                            ItemId = 13,
                            MaxQuantity = 3,
                            MinQuantity = 1,
                            MonsterId = 7
                        },
                        new
                        {
                            Id = 14,
                            DropRate = 60.0,
                            ItemId = 14,
                            MaxQuantity = 2,
                            MinQuantity = 1,
                            MonsterId = 8
                        },
                        new
                        {
                            Id = 15,
                            DropRate = 100.0,
                            ItemId = 15,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 9
                        },
                        new
                        {
                            Id = 16,
                            DropRate = 60.0,
                            ItemId = 17,
                            MaxQuantity = 3,
                            MinQuantity = 1,
                            MonsterId = 9
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpReward")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBoss")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 5,
                            CurrentHp = 30,
                            Defense = 2,
                            Description = "一團軟趴趴的黏液生物，對新手來說是很好的練習對象。",
                            ExpReward = 10,
                            IsBoss = false,
                            Level = 1,
                            LocationId = 4,
                            MaxHp = 30,
                            Name = "史萊姆"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 8,
                            CurrentHp = 20,
                            Defense = 1,
                            Description = "敏捷的小型齧齒動物，雖然弱小但攻擊迅速。",
                            ExpReward = 8,
                            IsBoss = false,
                            Level = 2,
                            LocationId = 4,
                            MaxHp = 20,
                            Name = "野鼠"
                        },
                        new
                        {
                            Id = 3,
                            Attack = 12,
                            CurrentHp = 100,
                            Defense = 3,
                            Description = "史萊姆族群的首領，體型巨大且極具威脅性。",
                            ExpReward = 80,
                            IsBoss = true,
                            Level = 5,
                            LocationId = 5,
                            MaxHp = 100,
                            Name = "史萊姆王"
                        },
                        new
                        {
                            Id = 4,
                            Attack = 12,
                            CurrentHp = 60,
                            Defense = 4,
                            Description = "森林中的掠食者，成群結隊狩獵，牙齒鋒利無比。",
                            ExpReward = 25,
                            IsBoss = false,
                            Level = 5,
                            LocationId = 7,
                            MaxHp = 60,
                            Name = "野狼"
                        },
                        new
                        {
                            Id = 5,
                            Attack = 15,
                            CurrentHp = 50,
                            Defense = 3,
                            Description = "狡猾的小型類人生物，喜歡在森林中埋伏旅人。",
                            ExpReward = 30,
                            IsBoss = false,
                            Level = 6,
                            LocationId = 9,
                            MaxHp = 50,
                            Name = "哥布林"
                        },
                        new
                        {
                            Id = 6,
                            Attack = 25,
                            CurrentHp = 200,
                            Defense = 8,
                            Description = "哥布林部落的首領，身披戰甲，揮舞著巨斧，是森林中最危險的存在。",
                            ExpReward = 150,
                            IsBoss = true,
                            Level = 10,
                            LocationId = 10,
                            MaxHp = 200,
                            Name = "哥布林酋長"
                        },
                        new
                        {
                            Id = 7,
                            Attack = 18,
                            CurrentHp = 80,
                            Defense = 6,
                            Description = "被黑暗魔法復活的亡者骨骸，永不疲倦地守護著礦坑。",
                            ExpReward = 45,
                            IsBoss = false,
                            Level = 10,
                            LocationId = 12,
                            MaxHp = 80,
                            Name = "骷髏"
                        },
                        new
                        {
                            Id = 8,
                            Attack = 20,
                            CurrentHp = 100,
                            Defense = 8,
                            Description = "腐爛的屍體被邪惡力量驅動，行動遲緩但力量驚人。",
                            ExpReward = 55,
                            IsBoss = false,
                            Level = 12,
                            LocationId = 13,
                            MaxHp = 100,
                            Name = "殭屍"
                        },
                        new
                        {
                            Id = 9,
                            Attack = 35,
                            CurrentHp = 300,
                            Defense = 10,
                            Description = "操控亡靈的邪惡法師，是礦坑中所有不死生物的主人。",
                            ExpReward = 250,
                            IsBoss = true,
                            Level = 15,
                            LocationId = 15,
                            MaxHp = 300,
                            Name = "死靈法師"
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.MonsterSpawn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EngagedPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InCombat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("KilledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonsterTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SpawnedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonsterTemplateId");

                    b.ToTable("MonsterSpawns");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.PlayerCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasePower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MpCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequiredClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ScalingMultiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("ScalingStat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePower = 20,
                            Cooldown = 3,
                            Description = "A powerful physical strike.",
                            MpCost = 5,
                            Name = "Bash",
                            RequiredClass = 0,
                            RequiredLevel = 1,
                            ScalingMultiplier = 1.5,
                            ScalingStat = "STR",
                            SkillId = "bash",
                            TargetType = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            BasePower = 0,
                            Cooldown = 10,
                            Description = "Force the enemy to focus on you.",
                            MpCost = 3,
                            Name = "Taunt",
                            RequiredClass = 0,
                            RequiredLevel = 3,
                            ScalingMultiplier = 0.0,
                            ScalingStat = "CON",
                            SkillId = "taunt",
                            TargetType = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            BasePower = 0,
                            Cooldown = 30,
                            Description = "Temporarily increase defense.",
                            MpCost = 10,
                            Name = "Iron Skin",
                            RequiredClass = 0,
                            RequiredLevel = 5,
                            ScalingMultiplier = 0.5,
                            ScalingStat = "CON",
                            SkillId = "ironskin",
                            TargetType = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            BasePower = 25,
                            Cooldown = 2,
                            Description = "Hurl a ball of fire at the enemy.",
                            MpCost = 10,
                            Name = "Fireball",
                            RequiredClass = 1,
                            RequiredLevel = 1,
                            ScalingMultiplier = 2.0,
                            ScalingStat = "INT",
                            SkillId = "fireball",
                            TargetType = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            BasePower = 15,
                            Cooldown = 10,
                            Description = "Unleash a storm of ice on all enemies.",
                            MpCost = 25,
                            Name = "Ice Storm",
                            RequiredClass = 1,
                            RequiredLevel = 5,
                            ScalingMultiplier = 1.5,
                            ScalingStat = "INT",
                            SkillId = "icestorm",
                            TargetType = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            BasePower = 0,
                            Cooldown = 60,
                            Description = "Convert damage to MP cost.",
                            MpCost = 20,
                            Name = "Mana Shield",
                            RequiredClass = 1,
                            RequiredLevel = 3,
                            ScalingMultiplier = 0.0,
                            ScalingStat = "INT",
                            SkillId = "manashield",
                            TargetType = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            BasePower = 30,
                            Cooldown = 3,
                            Description = "Restore HP to yourself.",
                            MpCost = 8,
                            Name = "Heal",
                            RequiredClass = 2,
                            RequiredLevel = 1,
                            ScalingMultiplier = 2.0,
                            ScalingStat = "WIS",
                            SkillId = "heal",
                            TargetType = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            BasePower = 0,
                            Cooldown = 30,
                            Description = "Increase STR and DEX temporarily.",
                            MpCost = 15,
                            Name = "Bless",
                            RequiredClass = 2,
                            RequiredLevel = 3,
                            ScalingMultiplier = 0.29999999999999999,
                            ScalingStat = "WIS",
                            SkillId = "bless",
                            TargetType = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            BasePower = 20,
                            Cooldown = 4,
                            Description = "Holy damage that scales with WIS.",
                            MpCost = 12,
                            Name = "Smite",
                            RequiredClass = 2,
                            RequiredLevel = 1,
                            ScalingMultiplier = 1.8,
                            ScalingStat = "WIS",
                            SkillId = "smite",
                            TargetType = 1,
                            Type = 1
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.WorldRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "你站在一個寧靜村莊的中心。一座噴泉在旁邊潺潺作響，村民們悠閒地走過。往東可見一片幽暗的森林入口。",
                            ExitsJson = "{\"n\":2,\"e\":6,\"s\":4,\"w\":3}",
                            Name = "新手村廣場",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "木製人偶排列成行。空氣中迴盪著木劍敲擊的聲音，幾位新手正在練習基本招式。",
                            ExitsJson = "{\"s\":1}",
                            Name = "練武場",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "一間溫馨的小屋，瀰漫著藥草的香氣。牆上掛滿古老的地圖和冒險者的紀念品。",
                            ExitsJson = "{\"e\":1}",
                            Name = "村長的小屋",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "村莊的邊緣地帶，青草隨風搖曳。你可以看到一些史萊姆在附近游蕩，偶爾有野鼠竄過。",
                            ExitsJson = "{\"n\":1,\"s\":5}",
                            Name = "村莊外圍",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "一片爬滿史萊姆的原野。牠們看起來大多無害，但被激怒時可能會攻擊。往南可見一個廢棄礦坑的入口...",
                            ExitsJson = "{\"n\":4,\"s\":11}",
                            Name = "史萊姆平原",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "高聳的樹木遮蔽了大部分陽光，空氣中瀰漫著潮濕的泥土味。你隱約聽到遠處傳來狼嚎聲...",
                            ExitsJson = "{\"w\":1,\"e\":7}",
                            Name = "低語森林入口",
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "蜿蜒的小徑穿過茂密的森林，地上到處可見野狼的腳印。偶爾可見樹幹上哥布林留下的奇怪記號。",
                            ExitsJson = "{\"w\":6,\"e\":8,\"s\":9}",
                            Name = "幽暗林道",
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "一棵巨大的橡樹矗立在森林深處，樹齡看起來有數百年。樹下堆滿了落葉和小動物的骨骸。",
                            ExitsJson = "{\"w\":7}",
                            Name = "古老橡樹",
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "簡陋的帳篷和篝火殘跡顯示這裡是哥布林的聚集地。空氣中飄散著腐臭的氣味，地上散落著啃食過的骨頭。",
                            ExitsJson = "{\"n\":7,\"s\":10}",
                            Name = "哥布林營地",
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "一個用樹枝和獸皮搭建的大型棚屋，這裡是哥布林酋長的領地。牆上掛滿了冒險者的裝備作為戰利品。",
                            ExitsJson = "{\"n\":9}",
                            Name = "酋長的巢穴",
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "一個被木頭支架撐起的礦坑入口，散發著陰冷潮濕的氣息。牆上的火把早已熄滅，只剩下漆黑的通道。",
                            ExitsJson = "{\"n\":5,\"s\":12}",
                            Name = "礦坑入口",
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "狹窄的隧道向下延伸，兩側是粗糙的岩壁。地上散落著生鏽的採礦工具和不明的白骨。",
                            ExitsJson = "{\"n\":11,\"s\":13,\"e\":14}",
                            Name = "昏暗隧道",
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "這裡曾經發生過嚴重的坍塌，巨石堵住了大部分通道。在碎石堆中，你可以看到骷髏正在四處遊蕩。",
                            ExitsJson = "{\"n\":12}",
                            Name = "崩塌礦井",
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 14,
                            Description = "礦坑深處竟然有一座古老的祭壇，上面刻滿了不祥的符文。空氣中瀰漫著死亡的氣息，殭屍在此徘徊。",
                            ExitsJson = "{\"w\":12,\"n\":15}",
                            Name = "詭異祭壇",
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "一間被黑暗能量籠罩的密室，牆上的燭火發出詭異的綠光。一位身披黑袍的死靈法師正在進行邪惡的儀式...",
                            ExitsJson = "{\"s\":14}",
                            Name = "死靈法師密室",
                            ZoneId = 3
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "適合新手冒險的安全區域",
                            MaxLevel = 5,
                            MinLevel = 1,
                            Name = "新手村"
                        },
                        new
                        {
                            Id = 2,
                            Description = "森林深處潛伏著危險的野獸和哥布林",
                            MaxLevel = 10,
                            MinLevel = 5,
                            Name = "低語森林"
                        },
                        new
                        {
                            Id = 3,
                            Description = "被亡靈佔據的古老礦坑，充滿死亡的氣息",
                            MaxLevel = 15,
                            MinLevel = 10,
                            Name = "廢棄礦坑"
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.ActiveCombat", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.MonsterSpawn", "MonsterSpawn")
                        .WithMany()
                        .HasForeignKey("MonsterSpawnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KingOfKings.Backend.Models.PlayerCharacter", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterSpawn");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.InventoryItem", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KingOfKings.Backend.Models.PlayerCharacter", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.LootTableEntry", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KingOfKings.Backend.Models.Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.MonsterSpawn", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.Monster", "MonsterTemplate")
                        .WithMany()
                        .HasForeignKey("MonsterTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterTemplate");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.PlayerCharacter", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KingOfKings.Backend.Models.CharacterStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("PlayerCharacterId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Con")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Dex")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Int")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Str")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Wis")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerCharacterId");

                            b1.ToTable("PlayerCharacters");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacterId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
