// <auto-generated />
using System;
using KingOfKings.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KingOfKings.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215084328_LocalizeZone1AndFixEquipment")]
    partial class LocalizeZone1AndFixEquipment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KingOfKings.Backend.Models.ActiveCombat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResting")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTick")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MonsterSpawnId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextTick")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueuedSkillId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonsterSpawnId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ActiveCombats");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquippedSlot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "史萊姆凝膠",
                            PropertiesJson = "{}",
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "野鼠尾巴",
                            PropertiesJson = "{}",
                            Type = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "新手之戒",
                            PropertiesJson = "{\"Str\":1,\"Int\":1,\"Wis\":1,\"Dex\":1,\"Con\":1}",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "生鏽的劍",
                            PropertiesJson = "{\"Atk\":5}",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "木杖",
                            PropertiesJson = "{\"Atk\":3,\"Int\":2}",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "生命藥水",
                            PropertiesJson = "{\"HealHp\":30}",
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "魔力藥水",
                            PropertiesJson = "{\"HealMp\":20}",
                            Type = 2
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.LootTableEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DropRate")
                        .HasColumnType("REAL");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonsterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("MonsterId");

                    b.ToTable("LootTableEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DropRate = 50.0,
                            ItemId = 1,
                            MaxQuantity = 2,
                            MinQuantity = 1,
                            MonsterId = 1
                        },
                        new
                        {
                            Id = 2,
                            DropRate = 60.0,
                            ItemId = 2,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 2
                        },
                        new
                        {
                            Id = 3,
                            DropRate = 100.0,
                            ItemId = 3,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 3
                        },
                        new
                        {
                            Id = 4,
                            DropRate = 15.0,
                            ItemId = 6,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 1
                        },
                        new
                        {
                            Id = 5,
                            DropRate = 15.0,
                            ItemId = 6,
                            MaxQuantity = 1,
                            MinQuantity = 1,
                            MonsterId = 2
                        },
                        new
                        {
                            Id = 6,
                            DropRate = 30.0,
                            ItemId = 7,
                            MaxQuantity = 2,
                            MinQuantity = 1,
                            MonsterId = 3
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpReward")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 5,
                            CurrentHp = 30,
                            Defense = 2,
                            ExpReward = 10,
                            LocationId = 4,
                            MaxHp = 30,
                            Name = "史萊姆"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 8,
                            CurrentHp = 20,
                            Defense = 1,
                            ExpReward = 8,
                            LocationId = 4,
                            MaxHp = 20,
                            Name = "野鼠"
                        },
                        new
                        {
                            Id = 3,
                            Attack = 12,
                            CurrentHp = 100,
                            Defense = 3,
                            ExpReward = 80,
                            LocationId = 5,
                            MaxHp = 100,
                            Name = "史萊姆王"
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.MonsterSpawn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EngagedPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InCombat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("KilledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonsterTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SpawnedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonsterTemplateId");

                    b.ToTable("MonsterSpawns");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.PlayerCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasePower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MpCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequiredClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ScalingMultiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("ScalingStat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePower = 20,
                            Cooldown = 3,
                            Description = "A powerful physical strike.",
                            MpCost = 5,
                            Name = "Bash",
                            RequiredClass = 0,
                            RequiredLevel = 1,
                            ScalingMultiplier = 1.5,
                            ScalingStat = "STR",
                            SkillId = "bash",
                            TargetType = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            BasePower = 0,
                            Cooldown = 10,
                            Description = "Force the enemy to focus on you.",
                            MpCost = 3,
                            Name = "Taunt",
                            RequiredClass = 0,
                            RequiredLevel = 3,
                            ScalingMultiplier = 0.0,
                            ScalingStat = "CON",
                            SkillId = "taunt",
                            TargetType = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            BasePower = 0,
                            Cooldown = 30,
                            Description = "Temporarily increase defense.",
                            MpCost = 10,
                            Name = "Iron Skin",
                            RequiredClass = 0,
                            RequiredLevel = 5,
                            ScalingMultiplier = 0.5,
                            ScalingStat = "CON",
                            SkillId = "ironskin",
                            TargetType = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            BasePower = 25,
                            Cooldown = 2,
                            Description = "Hurl a ball of fire at the enemy.",
                            MpCost = 10,
                            Name = "Fireball",
                            RequiredClass = 1,
                            RequiredLevel = 1,
                            ScalingMultiplier = 2.0,
                            ScalingStat = "INT",
                            SkillId = "fireball",
                            TargetType = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            BasePower = 15,
                            Cooldown = 10,
                            Description = "Unleash a storm of ice on all enemies.",
                            MpCost = 25,
                            Name = "Ice Storm",
                            RequiredClass = 1,
                            RequiredLevel = 5,
                            ScalingMultiplier = 1.5,
                            ScalingStat = "INT",
                            SkillId = "icestorm",
                            TargetType = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            BasePower = 0,
                            Cooldown = 60,
                            Description = "Convert damage to MP cost.",
                            MpCost = 20,
                            Name = "Mana Shield",
                            RequiredClass = 1,
                            RequiredLevel = 3,
                            ScalingMultiplier = 0.0,
                            ScalingStat = "INT",
                            SkillId = "manashield",
                            TargetType = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            BasePower = 30,
                            Cooldown = 3,
                            Description = "Restore HP to yourself.",
                            MpCost = 8,
                            Name = "Heal",
                            RequiredClass = 2,
                            RequiredLevel = 1,
                            ScalingMultiplier = 2.0,
                            ScalingStat = "WIS",
                            SkillId = "heal",
                            TargetType = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            BasePower = 0,
                            Cooldown = 30,
                            Description = "Increase STR and DEX temporarily.",
                            MpCost = 15,
                            Name = "Bless",
                            RequiredClass = 2,
                            RequiredLevel = 3,
                            ScalingMultiplier = 0.29999999999999999,
                            ScalingStat = "WIS",
                            SkillId = "bless",
                            TargetType = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            BasePower = 20,
                            Cooldown = 4,
                            Description = "Holy damage that scales with WIS.",
                            MpCost = 12,
                            Name = "Smite",
                            RequiredClass = 2,
                            RequiredLevel = 1,
                            ScalingMultiplier = 1.8,
                            ScalingStat = "WIS",
                            SkillId = "smite",
                            TargetType = 1,
                            Type = 1
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.WorldRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "你站在一個寧靜村莊的中心。一座噴泉在旁邊潺潺作響，村民們悠閒地走過。",
                            ExitsJson = "{\"n\":2,\"e\":3,\"s\":4}",
                            Name = "新手村廣場"
                        },
                        new
                        {
                            Id = 2,
                            Description = "木製人偶排列成行。空氣中迴盪著木劍敲擊的聲音，幾位新手正在練習基本招式。",
                            ExitsJson = "{\"s\":1}",
                            Name = "練武場"
                        },
                        new
                        {
                            Id = 3,
                            Description = "一間溫馨的小屋，瀰漫著藥草的香氣。牆上掛滿古老的地圖和冒險者的紀念品。",
                            ExitsJson = "{\"w\":1}",
                            Name = "村長的小屋"
                        },
                        new
                        {
                            Id = 4,
                            Description = "村莊的邊緣地帶，青草隨風搖曳。你可以看到一些史萊姆在附近游蕩，偶爾有野鼠竄過。",
                            ExitsJson = "{\"n\":1,\"s\":5}",
                            Name = "村莊外圍"
                        },
                        new
                        {
                            Id = 5,
                            Description = "一片爬滿史萊姆的原野。牠們看起來大多無害，但被激怒時可能會攻擊。傳說這裡偶爾會出現巨大的史萊姆王...",
                            ExitsJson = "{\"n\":4}",
                            Name = "史萊姆平原"
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.ActiveCombat", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.MonsterSpawn", "MonsterSpawn")
                        .WithMany()
                        .HasForeignKey("MonsterSpawnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KingOfKings.Backend.Models.PlayerCharacter", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterSpawn");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.InventoryItem", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KingOfKings.Backend.Models.PlayerCharacter", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.LootTableEntry", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KingOfKings.Backend.Models.Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.MonsterSpawn", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.Monster", "MonsterTemplate")
                        .WithMany()
                        .HasForeignKey("MonsterTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonsterTemplate");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.PlayerCharacter", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KingOfKings.Backend.Models.CharacterStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("PlayerCharacterId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Con")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Dex")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Int")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Str")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Wis")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerCharacterId");

                            b1.ToTable("PlayerCharacters");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacterId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
