// <auto-generated />
using System;
using KingOfKings.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KingOfKings.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121021210_FixUserIdType")]
    partial class FixUserIdType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KingOfKings.Backend.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.PlayerCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.WorldRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "You are standing in the center of a peaceful village. A fountain bubbles softly nearby.",
                            ExitsJson = "{\"n\":2,\"e\":3}",
                            Name = "Village Square"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Wooden dummies stand in rows here. The sound of striking wood fills the air.",
                            ExitsJson = "{\"s\":1}",
                            Name = "Training Grounds"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A cozy hut with the smell of herbs.",
                            ExitsJson = "{\"w\":1}",
                            Name = "Village Elder's House"
                        });
                });

            modelBuilder.Entity("KingOfKings.Backend.Models.PlayerCharacter", b =>
                {
                    b.HasOne("KingOfKings.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KingOfKings.Backend.Models.CharacterStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("PlayerCharacterId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Con")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Dex")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Int")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Str")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Wis")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerCharacterId");

                            b1.ToTable("PlayerCharacters");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacterId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
